name: Build and Tests

on: pull_request

jobs:
  build_tests_nuget_package:
    name: Build and Tests
    runs-on: ubuntu-latest
    steps:

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 10.0.x

      - uses: actions/checkout@v4
  
      - name: Restore Package
        run: dotnet restore ./src/VisionSharp/VisionSharp.csproj

      - name: Build Package
        run: dotnet build --no-restore  ./src/VisionSharp/VisionSharp.csproj

      - name: Clean
        run: dotnet clean

      - name: Run Unit Tests Package
        run: dotnet test ./tests/VisionSharp.UnitTests/VisionSharp.UnitTests.csproj

      - name: Run Integration Tests
        run: dotnet test ./tests/VisionSharp.IntegrationTests/VisionSharp.IntegrationTests.csproj
      
      
    
      
