name: Publish Nuget Packages

on:
  push:
    tags:
      - '*.*.**'
jobs:
  publish_nuget_package:
    name: Publish
    runs-on: ubuntu-latest
    steps:

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 10.0.x
      
      - uses: actions/checkout@v4
      - name: Set Version 
        run: |
          sed -i -e 's/1.1.1/${{github.ref_name}}/' ./src/VisionSharp/VisionSharp.csproj

      - name: Clean
        run: dotnet clean ./src/VisionSharp/VisionSharp.csproj

      - name: Restore 
        run: dotnet restore ./src/VisionSharp/VisionSharp.csproj

      - name: Build
        run: dotnet build --no-restore -c Release ./src/VisionSharp/VisionSharp.csproj

      - name: Pack 
        run: |
          dotnet pack ./src/VisionSharp/VisionSharp.csproj -c Release -o output-client


      - name: Publish Client to Nuget.Org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push output-client/*.nupkg -s https://api.nuget.org/v3/index.json --skip-duplicate
      
    
      
      
